services:

  app:
    build: .
    container_name: sgp_app

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev

    depends_on:
      - postgres

  postgres:

    image: postgres:17

    container_name: sgp_db

    restart: always

    environment:
      POSTGRES_DB: sgp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:

    image: dpage/pgadmin4

    container_name: sgp_pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

volumes:

  postgres_data: